/* this file was generated by linkcmd.xdt from the gnu.targets.arm
 * package
 */
INPUT(
    /usr/local/dvsdk/c6accel_1_01_00_06/soc/app/c6accel_app_config/package/cfg/c6accel_app_xv5T.ov5T
    /usr/local/dvsdk/codec_engine_2_26_02_11/packages/ti/sdo/ce/universal/lib/release/universal.av5T
    /usr/local/dvsdk/codec_engine_2_26_02_11/packages/ti/sdo/ce/lib/release/ce.av5T
    /usr/local/dvsdk/codec_engine_2_26_02_11/packages/ti/sdo/ce/alg/lib/release/Algorithm_noOS.av5T
    /usr/local/dvsdk/codec_engine_2_26_02_11/packages/ti/sdo/ce/alg/lib/release/alg.av5T
    /usr/local/dvsdk/codec_engine_2_26_02_11/packages/ti/sdo/ce/ipc/dsplink/lib/release/ipc_dsplink_3530.av5T
    /usr/local/dvsdk/codec_engine_2_26_02_11/packages/ti/sdo/ce/osal/linux/lib/release/osal_linux_470.av5T
    /usr/local/dvsdk/framework-components_2_26_00_01/packages/ti/sdo/fc/acpy3/lib/release/acpy3.a470MV
    /usr/local/dvsdk/framework-components_2_26_00_01/packages/ti/sdo/fc/dman3/lib/release/dman3Cfg.a470MV
    /usr/local/dvsdk/framework-components_2_26_00_01/packages/ti/sdo/fc/utils/lib/release/rmm.av5T
    /usr/local/dvsdk/framework-components_2_26_00_01/packages/ti/sdo/fc/utils/lib/release/smgr.av5T
    /usr/local/dvsdk/framework-components_2_26_00_01/packages/ti/sdo/fc/utils/lib/release/rmmp.av5T
    /usr/local/dvsdk/framework-components_2_26_00_01/packages/ti/sdo/fc/utils/lib/release/smgrmp.av5T
    /usr/local/dvsdk/framework-components_2_26_00_01/packages/ti/sdo/fc/utils/lib/release/shm.av5T
    /usr/local/dvsdk/framework-components_2_26_00_01/packages/ti/sdo/fc/memutils/lib/release/memutils.av5T
    /usr/local/dvsdk/codec_engine_2_26_02_11/packages/ti/sdo/ce/utils/xdm/lib/release/XdmUtils.av5T
    /usr/local/dvsdk/framework-components_2_26_00_01/packages/ti/sdo/utils/trace/lib/release/gt.av5T
    /usr/local/dvsdk/codec_engine_2_26_02_11/packages/ti/sdo/ce/node/lib/release/node.av5T
    /usr/local/dvsdk/local-power-manager_1_24_02_09/packages/ti/bios/power/lib/release/lpm.av5T
    /usr/local/dvsdk/dsplink_1_65_00_02/dsplink/gpp/export/BIN/Linux/OMAP3530/RELEASE/dsplink.lib
    /usr/local/dvsdk/framework-components_2_26_00_01/packages/ti/sdo/fc/scpy/lib/release/scpy.av5T
    /usr/local/dvsdk/linuxutils_2_26_01_02/packages/ti/sdo/linuxutils/cmem/lib/cmem.a470MV
    /usr/local/dvsdk/linuxutils_2_26_01_02/packages/ti/sdo/linuxutils/sdma/lib/sdma.a470MV
    /usr/local/dvsdk/xdctools_3_16_03_36/packages/gnu/targets/arm/rtsv5T/lib/gnu.targets.arm.rtsv5T.av5T
)

